user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    client_max_body_size 0;
    server_tokens off;
    include /etc/nginx/mime.types;

    server {
        listen 80;
        server_name madagasycar.com www.madagasycar.com;

        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }

        location / {
            return 301 https://madagasycar.com$request_uri;
        }
    }

    server {
        listen 443 ssl;
        server_name madagasycar.com www.madagasycar.com;

        ssl_certificate /etc/letsencrypt/live/madagasycar.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/madagasycar.com/privkey.pem;

        location / {
            proxy_pass http://react_frontend:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/ {
            proxy_pass http://django_backend:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /media/ {
            alias /app/media/;
        }

        location /static/ {
            alias /app/static/;
        }
    }
}
