name: Build and Deploy

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy to Remote Server
        run: |
          sshpass -p "${{ secrets.SERVER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          set -e

          cd prod-ci-cd-gasycar-main

          git reset --hard
          git pull origin main

          docker compose down

          if [ ! -d "./certbot/conf/live/madagasycar.com" ]; then
            docker run --rm -p 80:80 \
              -v "$(pwd)/certbot/conf:/etc/letsencrypt" \
              -v "$(pwd)/certbot/www:/var/www/certbot" \
              certbot/certbot certonly --standalone \
              -d madagasycar.com \
              -d www.madagasycar.com \
              --email devworkshop26@gmail.com \
              --agree-tos \
              --no-eff-email
          fi

          docker compose pull
          docker compose up -d

          docker system prune -f
          EOF
